# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from retell_ai_python_sdk import schemas  # noqa: F401


class CallMakeConnectionRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "phone_number",
        }
        
        class properties:
        
            @staticmethod
            def phone_number() -> typing.Type['CallMakeConnectionRequestPhoneNumber']:
                return CallMakeConnectionRequestPhoneNumber
            override_agent_id = schemas.StrSchema
        
            @staticmethod
            def retell_llm_dynamic_variables() -> typing.Type['CallMakeConnectionRequestRetellLlmDynamicVariables']:
                return CallMakeConnectionRequestRetellLlmDynamicVariables
            __annotations__ = {
                "phone_number": phone_number,
                "override_agent_id": override_agent_id,
                "retell_llm_dynamic_variables": retell_llm_dynamic_variables,
            }
    
    phone_number: 'CallMakeConnectionRequestPhoneNumber'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone_number"]) -> 'CallMakeConnectionRequestPhoneNumber': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["override_agent_id"]) -> MetaOapg.properties.override_agent_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["retell_llm_dynamic_variables"]) -> 'CallMakeConnectionRequestRetellLlmDynamicVariables': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["phone_number", "override_agent_id", "retell_llm_dynamic_variables", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone_number"]) -> 'CallMakeConnectionRequestPhoneNumber': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["override_agent_id"]) -> typing.Union[MetaOapg.properties.override_agent_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["retell_llm_dynamic_variables"]) -> typing.Union['CallMakeConnectionRequestRetellLlmDynamicVariables', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["phone_number", "override_agent_id", "retell_llm_dynamic_variables", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        phone_number: 'CallMakeConnectionRequestPhoneNumber',
        override_agent_id: typing.Union[MetaOapg.properties.override_agent_id, str, schemas.Unset] = schemas.unset,
        retell_llm_dynamic_variables: typing.Union['CallMakeConnectionRequestRetellLlmDynamicVariables', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CallMakeConnectionRequest':
        return super().__new__(
            cls,
            *args,
            phone_number=phone_number,
            override_agent_id=override_agent_id,
            retell_llm_dynamic_variables=retell_llm_dynamic_variables,
            _configuration=_configuration,
            **kwargs,
        )

from retell_ai_python_sdk.model.call_make_connection_request_phone_number import CallMakeConnectionRequestPhoneNumber
from retell_ai_python_sdk.model.call_make_connection_request_retell_llm_dynamic_variables import CallMakeConnectionRequestRetellLlmDynamicVariables
