# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from retell_ai_python_sdk import schemas  # noqa: F401


class CallBase(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "call_status",
            "agent_id",
            "sample_rate",
            "audio_encoding",
            "start_timestamp",
            "audio_websocket_protocol",
            "call_id",
        }
        
        class properties:
            call_id = schemas.StrSchema
            agent_id = schemas.StrSchema
            
            
            class audio_websocket_protocol(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def WEB(cls):
                    return cls("web")
                
                @schemas.classproperty
                def TWILIO(cls):
                    return cls("twilio")
            
            
            class audio_encoding(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def S16LE(cls):
                    return cls("s16le")
                
                @schemas.classproperty
                def MULAW(cls):
                    return cls("mulaw")
            sample_rate = schemas.IntSchema
            
            
            class call_status(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def REGISTERED(cls):
                    return cls("registered")
                
                @schemas.classproperty
                def ONGOING(cls):
                    return cls("ongoing")
                
                @schemas.classproperty
                def ENDED(cls):
                    return cls("ended")
                
                @schemas.classproperty
                def ERROR(cls):
                    return cls("error")
            start_timestamp = schemas.IntSchema
            end_call_after_silence_ms = schemas.IntSchema
            from_number = schemas.StrSchema
            to_number = schemas.StrSchema
            metadata = schemas.DictSchema
        
            @staticmethod
            def retell_llm_dynamic_variables() -> typing.Type['CallBaseRetellLlmDynamicVariables']:
                return CallBaseRetellLlmDynamicVariables
            __annotations__ = {
                "call_id": call_id,
                "agent_id": agent_id,
                "audio_websocket_protocol": audio_websocket_protocol,
                "audio_encoding": audio_encoding,
                "sample_rate": sample_rate,
                "call_status": call_status,
                "start_timestamp": start_timestamp,
                "end_call_after_silence_ms": end_call_after_silence_ms,
                "from_number": from_number,
                "to_number": to_number,
                "metadata": metadata,
                "retell_llm_dynamic_variables": retell_llm_dynamic_variables,
            }
    
    call_status: MetaOapg.properties.call_status
    agent_id: MetaOapg.properties.agent_id
    sample_rate: MetaOapg.properties.sample_rate
    audio_encoding: MetaOapg.properties.audio_encoding
    start_timestamp: MetaOapg.properties.start_timestamp
    audio_websocket_protocol: MetaOapg.properties.audio_websocket_protocol
    call_id: MetaOapg.properties.call_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["call_id"]) -> MetaOapg.properties.call_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["agent_id"]) -> MetaOapg.properties.agent_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audio_websocket_protocol"]) -> MetaOapg.properties.audio_websocket_protocol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["audio_encoding"]) -> MetaOapg.properties.audio_encoding: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sample_rate"]) -> MetaOapg.properties.sample_rate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["call_status"]) -> MetaOapg.properties.call_status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_timestamp"]) -> MetaOapg.properties.start_timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["end_call_after_silence_ms"]) -> MetaOapg.properties.end_call_after_silence_ms: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["from_number"]) -> MetaOapg.properties.from_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["to_number"]) -> MetaOapg.properties.to_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["retell_llm_dynamic_variables"]) -> 'CallBaseRetellLlmDynamicVariables': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["call_id", "agent_id", "audio_websocket_protocol", "audio_encoding", "sample_rate", "call_status", "start_timestamp", "end_call_after_silence_ms", "from_number", "to_number", "metadata", "retell_llm_dynamic_variables", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["call_id"]) -> MetaOapg.properties.call_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["agent_id"]) -> MetaOapg.properties.agent_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audio_websocket_protocol"]) -> MetaOapg.properties.audio_websocket_protocol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["audio_encoding"]) -> MetaOapg.properties.audio_encoding: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sample_rate"]) -> MetaOapg.properties.sample_rate: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["call_status"]) -> MetaOapg.properties.call_status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_timestamp"]) -> MetaOapg.properties.start_timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["end_call_after_silence_ms"]) -> typing.Union[MetaOapg.properties.end_call_after_silence_ms, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["from_number"]) -> typing.Union[MetaOapg.properties.from_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["to_number"]) -> typing.Union[MetaOapg.properties.to_number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union[MetaOapg.properties.metadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["retell_llm_dynamic_variables"]) -> typing.Union['CallBaseRetellLlmDynamicVariables', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["call_id", "agent_id", "audio_websocket_protocol", "audio_encoding", "sample_rate", "call_status", "start_timestamp", "end_call_after_silence_ms", "from_number", "to_number", "metadata", "retell_llm_dynamic_variables", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        call_status: typing.Union[MetaOapg.properties.call_status, str, ],
        agent_id: typing.Union[MetaOapg.properties.agent_id, str, ],
        sample_rate: typing.Union[MetaOapg.properties.sample_rate, decimal.Decimal, int, ],
        audio_encoding: typing.Union[MetaOapg.properties.audio_encoding, str, ],
        start_timestamp: typing.Union[MetaOapg.properties.start_timestamp, decimal.Decimal, int, ],
        audio_websocket_protocol: typing.Union[MetaOapg.properties.audio_websocket_protocol, str, ],
        call_id: typing.Union[MetaOapg.properties.call_id, str, ],
        end_call_after_silence_ms: typing.Union[MetaOapg.properties.end_call_after_silence_ms, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        from_number: typing.Union[MetaOapg.properties.from_number, str, schemas.Unset] = schemas.unset,
        to_number: typing.Union[MetaOapg.properties.to_number, str, schemas.Unset] = schemas.unset,
        metadata: typing.Union[MetaOapg.properties.metadata, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        retell_llm_dynamic_variables: typing.Union['CallBaseRetellLlmDynamicVariables', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CallBase':
        return super().__new__(
            cls,
            *args,
            call_status=call_status,
            agent_id=agent_id,
            sample_rate=sample_rate,
            audio_encoding=audio_encoding,
            start_timestamp=start_timestamp,
            audio_websocket_protocol=audio_websocket_protocol,
            call_id=call_id,
            end_call_after_silence_ms=end_call_after_silence_ms,
            from_number=from_number,
            to_number=to_number,
            metadata=metadata,
            retell_llm_dynamic_variables=retell_llm_dynamic_variables,
            _configuration=_configuration,
            **kwargs,
        )

from retell_ai_python_sdk.model.call_base_retell_llm_dynamic_variables import CallBaseRetellLlmDynamicVariables
