# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from retell_ai_python_sdk import schemas  # noqa: F401


class PhoneNumberResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "agent_id",
            "area_code",
            "phone_number",
            "phone_number_pretty",
            "last_modification_timestamp",
        }
        
        class properties:
            phone_number = schemas.StrSchema
            phone_number_pretty = schemas.StrSchema
            agent_id = schemas.StrSchema
            area_code = schemas.IntSchema
            last_modification_timestamp = schemas.IntSchema
            __annotations__ = {
                "phone_number": phone_number,
                "phone_number_pretty": phone_number_pretty,
                "agent_id": agent_id,
                "area_code": area_code,
                "last_modification_timestamp": last_modification_timestamp,
            }
    
    agent_id: MetaOapg.properties.agent_id
    area_code: MetaOapg.properties.area_code
    phone_number: MetaOapg.properties.phone_number
    phone_number_pretty: MetaOapg.properties.phone_number_pretty
    last_modification_timestamp: MetaOapg.properties.last_modification_timestamp
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone_number"]) -> MetaOapg.properties.phone_number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone_number_pretty"]) -> MetaOapg.properties.phone_number_pretty: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["agent_id"]) -> MetaOapg.properties.agent_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["area_code"]) -> MetaOapg.properties.area_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["last_modification_timestamp"]) -> MetaOapg.properties.last_modification_timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["phone_number", "phone_number_pretty", "agent_id", "area_code", "last_modification_timestamp", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone_number"]) -> MetaOapg.properties.phone_number: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone_number_pretty"]) -> MetaOapg.properties.phone_number_pretty: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["agent_id"]) -> MetaOapg.properties.agent_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["area_code"]) -> MetaOapg.properties.area_code: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["last_modification_timestamp"]) -> MetaOapg.properties.last_modification_timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["phone_number", "phone_number_pretty", "agent_id", "area_code", "last_modification_timestamp", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        agent_id: typing.Union[MetaOapg.properties.agent_id, str, ],
        area_code: typing.Union[MetaOapg.properties.area_code, decimal.Decimal, int, ],
        phone_number: typing.Union[MetaOapg.properties.phone_number, str, ],
        phone_number_pretty: typing.Union[MetaOapg.properties.phone_number_pretty, str, ],
        last_modification_timestamp: typing.Union[MetaOapg.properties.last_modification_timestamp, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PhoneNumberResponse':
        return super().__new__(
            cls,
            *args,
            agent_id=agent_id,
            area_code=area_code,
            phone_number=phone_number,
            phone_number_pretty=phone_number_pretty,
            last_modification_timestamp=last_modification_timestamp,
            _configuration=_configuration,
            **kwargs,
        )
