# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from retell_ai_python_sdk import schemas  # noqa: F401


class PhoneNumberPurchaseNumberAndBindAgentRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "agent_id",
        }
        
        class properties:
            agent_id = schemas.StrSchema
            area_code = schemas.IntSchema
            __annotations__ = {
                "agent_id": agent_id,
                "area_code": area_code,
            }
    
    agent_id: MetaOapg.properties.agent_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["agent_id"]) -> MetaOapg.properties.agent_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["area_code"]) -> MetaOapg.properties.area_code: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["agent_id", "area_code", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["agent_id"]) -> MetaOapg.properties.agent_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["area_code"]) -> typing.Union[MetaOapg.properties.area_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["agent_id", "area_code", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        agent_id: typing.Union[MetaOapg.properties.agent_id, str, ],
        area_code: typing.Union[MetaOapg.properties.area_code, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PhoneNumberPurchaseNumberAndBindAgentRequest':
        return super().__new__(
            cls,
            *args,
            agent_id=agent_id,
            area_code=area_code,
            _configuration=_configuration,
            **kwargs,
        )
