# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from retell_ai_python_sdk import schemas  # noqa: F401


class RetellLLMBase(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            general_prompt = schemas.StrSchema
            
            
            class general_tools(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Tool']:
                        return Tool
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Tool'], typing.List['Tool']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'general_tools':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Tool':
                    return super().__getitem__(i)
            
            
            class states(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['State']:
                        return State
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['State'], typing.List['State']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'states':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'State':
                    return super().__getitem__(i)
            starting_state = schemas.StrSchema
            begin_message = schemas.StrSchema
            __annotations__ = {
                "general_prompt": general_prompt,
                "general_tools": general_tools,
                "states": states,
                "starting_state": starting_state,
                "begin_message": begin_message,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["general_prompt"]) -> MetaOapg.properties.general_prompt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["general_tools"]) -> MetaOapg.properties.general_tools: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["states"]) -> MetaOapg.properties.states: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["starting_state"]) -> MetaOapg.properties.starting_state: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["begin_message"]) -> MetaOapg.properties.begin_message: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["general_prompt", "general_tools", "states", "starting_state", "begin_message", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["general_prompt"]) -> typing.Union[MetaOapg.properties.general_prompt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["general_tools"]) -> typing.Union[MetaOapg.properties.general_tools, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["states"]) -> typing.Union[MetaOapg.properties.states, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["starting_state"]) -> typing.Union[MetaOapg.properties.starting_state, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["begin_message"]) -> typing.Union[MetaOapg.properties.begin_message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["general_prompt", "general_tools", "states", "starting_state", "begin_message", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        general_prompt: typing.Union[MetaOapg.properties.general_prompt, str, schemas.Unset] = schemas.unset,
        general_tools: typing.Union[MetaOapg.properties.general_tools, list, tuple, schemas.Unset] = schemas.unset,
        states: typing.Union[MetaOapg.properties.states, list, tuple, schemas.Unset] = schemas.unset,
        starting_state: typing.Union[MetaOapg.properties.starting_state, str, schemas.Unset] = schemas.unset,
        begin_message: typing.Union[MetaOapg.properties.begin_message, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RetellLLMBase':
        return super().__new__(
            cls,
            *args,
            general_prompt=general_prompt,
            general_tools=general_tools,
            states=states,
            starting_state=starting_state,
            begin_message=begin_message,
            _configuration=_configuration,
            **kwargs,
        )

from retell_ai_python_sdk.model.state import State
from retell_ai_python_sdk.model.tool import Tool
