# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from retell_ai_python_sdk.paths.create_agent.post import CreateNewAgent
from retell_ai_python_sdk.paths.delete_agent_agent_id.delete import DeleteExistingAgent
from retell_ai_python_sdk.paths.list_agents.get import GetAll
from retell_ai_python_sdk.paths.get_agent_agent_id.get import GetDetails
from retell_ai_python_sdk.paths.update_agent_agent_id.patch import UpdateExistingAgent
from retell_ai_python_sdk.apis.tags.agent_api_raw import AgentApiRaw


class AgentApi(
    CreateNewAgent,
    DeleteExistingAgent,
    GetAll,
    GetDetails,
    UpdateExistingAgent,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AgentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AgentApiRaw(api_client)
