# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from retell_ai_python_sdk.paths.register_call.post import EstablishConnectionRaw
from retell_ai_python_sdk.paths.get_call_call_id.get import GetDetailsRaw
from retell_ai_python_sdk.paths.list_calls.get import GetDetails0Raw
from retell_ai_python_sdk.paths.create_phone_call.post import MakeConnectionRaw


class CallApiRaw(
    EstablishConnectionRaw,
    GetDetailsRaw,
    GetDetails0Raw,
    MakeConnectionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
