# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from retell_ai_python_sdk.paths.list_phone_numbers.get import GetAllNumbers
from retell_ai_python_sdk.paths.get_phone_number_phone_number.get import GetDetails
from retell_ai_python_sdk.paths.create_phone_number.post import PurchaseNumberAndBindAgent
from retell_ai_python_sdk.paths.delete_phone_number_phone_number.delete import RemovePhoneNumber
from retell_ai_python_sdk.paths.update_phone_number_phone_number.patch import UpdateRetellLlm
from retell_ai_python_sdk.apis.tags.phone_number_api_raw import PhoneNumberApiRaw


class PhoneNumberApi(
    GetAllNumbers,
    GetDetails,
    PurchaseNumberAndBindAgent,
    RemovePhoneNumber,
    UpdateRetellLlm,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PhoneNumberApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PhoneNumberApiRaw(api_client)
