# coding: utf-8

"""
    Retell SDK

    API for voice AI. Effortlessly integrate human-like Voice AI into your product. | We are building an API that enables your product to provide an intuitive and engaging way for user interaction - through voice.

    The version of the OpenAPI document: 1.0.0
    Contact: founders@retellai.com
    Created by: https://www.retellai.com/
"""

from retell_ai_python_sdk.paths.delete_retell_llm_llm_id.delete import DeleteLlm
from retell_ai_python_sdk.paths.get_retell_llm_llm_id.get import GetLlmDetails
from retell_ai_python_sdk.paths.create_retell_llm.post import NewLlm
from retell_ai_python_sdk.paths.update_retell_llm_llm_id.patch import UpdateLlm
from retell_ai_python_sdk.apis.tags.retell_api_raw import RetellApiRaw


class RetellApi(
    DeleteLlm,
    GetLlmDetails,
    NewLlm,
    UpdateLlm,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RetellApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RetellApiRaw(api_client)
